import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Button } from "@/components/ui/button";
import Link from "next/link";

interface MenubarButtonProps {
  displayName: string;
  href: string;
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menubarButtons: MenubarButtonProps[] = [
  {
    displayName: "7Racing logo",
    href: "/",
  },
  {
    displayName: "Team",
    href: "/team",
  },
  {
    displayName: "Blog",
    href: "/blog",
  },
];

const MenubarButton = ({ displayName, href }: MenubarButtonProps) => {
  return (
    <div className="m-2">
      <Button variant="ghost" asChild>
        <Link href={href}>
          <div className="font-bold text-xl">{displayName}</div>
        </Link>
      </Button>
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row border border-black justify-between items-center">
          <div className="flex flex-row">
            {menubarButtons.map((button) => {
              return (
                <MenubarButton
                  displayName={button.displayName}
                  href={button.href}
                />
              );
            })}
          </div>
          social media icons
        </div>
        {children}
      </body>
    </html>
  );
}
