import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";

interface MenubarButtonProps {
  displayName: string;
  href: string;
  imagePath?: string;
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menubarButtons: MenubarButtonProps[] = [
  {
    displayName: "7Racing logo",
    href: "/",
    imagePath: "/logo-bg.png",
  },
  {
    displayName: "Team",
    href: "/team",
  },
  {
    displayName: "Blog",
    href: "/blog",
  },
];

const Menubar = () => {
  return (
    <div className="fixed flex flex-row border border-grey justify-between items-center top-0 left-0 right-0 z-50 bg-white">
      <div className="flex flex-row">
        {menubarButtons.map(({ displayName, href, imagePath }) => {
          return (
            <div className="m-2">
              <Button variant="ghost" asChild>
                <Link href={href}>
                  {imagePath ? (
                    <Image
                      src={imagePath}
                      width={36}
                      height={36}
                      alt={displayName}
                    />
                  ) : (
                    <div className="font-bold text-xl">{displayName}</div>
                  )}
                </Link>
              </Button>
            </div>
          );
        })}
      </div>
      <div className="flex flex-row">
        <a
          href="https://www.linkedin.com/company/yeditepe-university-seven-racing"
          target="_blank"
        >
          <Image
            src="/linkedin.png"
            width={36}
            height={36}
            alt="Linkedin logo"
            className="m-2"
          />
        </a>
        <a
          href="https://www.instagram.com/yeditepesevenracing/"
          target="_blank"
        >
          <Image
            src="/ig.svg"
            width={36}
            height={36}
            alt="Instagram logo"
            className="m-2"
          />
        </a>
        <a href="https://github.com/yeditepesevenracing" target="_blank">
          <Image
            src="/gh.svg"
            width={36}
            height={36}
            alt="GitHub logo"
            className="m-2"
          />
        </a>
      </div>
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menubar />
        <div className="pt-[64px] overflow-auto">{children}</div>
      </body>
    </html>
  );
}
